### ISSUE TITLE
Greek translation

### ISSUE THREAD

**Issue by DJDBgr** [userdatamanifesto/www#21]
Hello. I just wrote about User Data Manifesto 2.0 on my Greek tech blog, [DJDB.me](http://djdb.me/post/128065647910/user-data-manifesto). I'd lke to contribute to the project by translating the manifesto in Greek. Since i'm new to Github (and it looks a bit complicated, since i'm not a developer), which .po files should i translate and how/where should i upload the translated ones?

Thanks in advance!

**Comment by karlitschek** [comment]
Thanks for your offer :-)
@hugoroy @jancborchardt What do you suggest how to do this?

**Comment by hugoroy** [comment]
Sorry but at the moment, there are some issues about the translation, so while you can translate the po file [1], I will not show it on the website until the issues are resolved.

[1]: https://github.com/userdatamanifesto/www/blob/master/index.el.po

**Comment by DJDBgr** [comment]
It's ok. I'll translate this file and post it here. You may show it whenever these problems are resolved, no problem.

I guess there is a way to link someone to the translated manifesto, even if it's not linked on the website, right?

**Comment by hugoroy** [comment]
Great, thank you for the translation.

My issues is that the translation system is unreliable at the moment. So some translations were not showing up properly (for instance, only 50% of the translation would show up and leave the rest in English although the source file had 100% translated).

**Comment by DJDBgr** [comment]
I have already started the translation process using [Poedit](https://poedit.net/), after creating a new fork of index.el.po. I'll just make a new pull request when i'm ready (guess that's the correct process).

**Comment by hugoroy** [comment]
Perfect!
